name: Download and Commit Video using Git LFS

on: [workflow_dispatch]  # Manually trigger the workflow

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Enable Git LFS

      - name: Install gdown
        run: pip install gdown

      - name: Download Video from Google Drive
        run: |
          gdown --id 1GGtvDWqLZQieNmVhp0CG5pmg2LDFu4bE --output video.mp4

      - name: Install Git LFS
        run: |
          git lfs install
          git lfs track "*.mp4"
          git add .gitattributes

      - name: Commit and Push Video File
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPO_NAME: avakens139/test  # Your repo
        run: |
          git config --global user.name "avakens139"
          git config --global user.email "github-actions@github.com"
          git add video.mp4
          git commit -m "Add downloaded video using Git LFS"
          git push https://x-access-token:$GITHUB_TOKEN@github.com/$REPO_NAME.git HEAD:main
